In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas_datareader as dr

In [148]:
start_date = '2021-01-01'
end_date = '2021-01-10'

usdjpy = dr.data.DataReader('USDJPY%3DX', data_source='yahoo', start=start_date, end=end_date)
usdpgk = dr.data.DataReader('USDPGK%3DX', data_source='yahoo', start=start_date, end=end_date)
usdxpf = dr.data.DataReader('USDXPF%3DX', data_source='yahoo', start=start_date, end=end_date)
usdmga = dr.data.DataReader('USDMGA%3DX', data_source='yahoo', start=start_date, end=end_date)
usdeur = dr.data.DataReader('EURUSD%3DX', data_source='yahoo', start=start_date, end=end_date)

usdjpy.drop(["High","Low","Open","Volume","Adj Close"], axis=1,inplace=True)
usdpgk.drop(["High","Low","Open","Volume","Adj Close"], axis=1,inplace=True)
usdxpf.drop(["High","Low","Open","Volume","Adj Close"], axis=1,inplace=True)
usdmga.drop(["High","Low","Open","Volume","Adj Close"], axis=1,inplace=True)
usdeur.drop(["High","Low","Open","Volume","Adj Close"], axis=1,inplace=True)


usdjpy["name"]="JPY"
usdpgk["name"]="PGK"
usdxpf["name"]="XPF"
usdmga["name"]="MGA"
usdeur["name"]="EUR"

usdjpy = usdjpy[["name"] + usdjpy.columns[:-1].tolist()]
usdpgk = usdpgk[["name"] + usdpgk.columns[:-1].tolist()]
usdxpf = usdxpf[["name"] + usdxpf.columns[:-1].tolist()]
usdmga = usdmga[["name"] + usdmga.columns[:-1].tolist()]
usdeur = usdeur[["name"] + usdeur.columns[:-1].tolist()]


usdjpy.rename(columns ={'Close':'value'},inplace=True)
usdpgk.rename(columns ={'Close':'value'},inplace=True)
usdxpf.rename(columns ={'Close':'value'},inplace=True)
usdmga.rename(columns ={'Close':'value'},inplace=True)
usdeur.rename(columns ={'Close':'value'},inplace=True)

Currency=pd.concat([usdjpy,usdpgk,usdxpf,usdmga,usdeur],axis=0)
Currency.sort_values("name")
Currency

           name        value
Date
2021-01-01  JPY   103.225998
2021-01-04  JPY   103.238998
2021-01-05  JPY   103.125000
2021-01-06  JPY   102.678001
2021-01-07  JPY   103.024002
2021-01-08  JPY   103.790001
2021-01-11  JPY   104.091003
2021-01-01  PGK     3.455000
2021-01-04  PGK     3.508289
2021-01-05  PGK     3.450000
2021-01-06  PGK     3.465000
2021-01-07  PGK     3.450000
2021-01-08  PGK     3.455000
2021-01-11  PGK     3.460777
2021-01-01  XPF    97.000000
2021-01-04  XPF    97.599998
2021-01-05  XPF    97.150002
2021-01-06  XPF    97.000000
2021-01-07  XPF    97.000000
2021-01-08  XPF    97.349998
2021-01-11  XPF    97.599998
2021-01-01  MGA  3800.000000
2021-01-04  MGA  3830.000000
2021-01-05  MGA  3830.000000
2021-01-06  MGA  3780.000000
2021-01-07  MGA  3735.000000
2021-01-08  MGA  3745.000000
2021-01-11  MGA  3781.136963
2021-01-01  EUR     1.218027
2021-01-04  EUR     1.225070
2021-01-05  EUR     1.225160
2021-01-06  EUR     1.230027
2021-01-07  EUR     1.234111
2021-01-08  EUR     1.227144
2021-01-11  EUR     1.218621

In [151]:
 Currency.to_csv('Currency.csv', index=False)